import typing

class Error(Exception): ...

class Invalid(Error):
    def __init__(
        self, message, path=..., error_message=..., error_type=...
    ) -> None: ...

class MultipleInvalid(Invalid):
    def __init__(self, errors: typing.Optional[list[Invalid]] = None) -> None: ...
