"""
This type stub file was generated by pyright.
"""

MAX_VALIDATION_ERROR_ITEM_LENGTH = ...
def humanize_error(data, validation_error, max_sub_error_length=...): # -> LiteralString | str:
    """ Provide a more helpful + complete validation error message than that provided automatically
    Invalid and MultipleInvalid do not include the offending value in error messages,
    and MultipleInvalid.__str__ only provides the first error.
    """
    ...

def validate_with_humanized_errors(data, schema, max_sub_error_length=...):
    ...

