"""
This type stub file was generated by pyright.
"""

from typing import Any
from homeassistant import data_entry_flow
from homeassistant.components import websocket_api
from homeassistant.core import HomeAssistant, callback

"""Helpers to setup multi-factor auth module."""
WS_TYPE_SETUP_MFA = ...
SCHEMA_WS_SETUP_MFA = ...
WS_TYPE_DEPOSE_MFA = ...
SCHEMA_WS_DEPOSE_MFA = ...
DATA_SETUP_FLOW_MGR = ...
_LOGGER = ...
class MfaFlowManager(data_entry_flow.FlowManager):
    """Manage multi factor authentication flows."""
    async def async_create_flow(self, handler_key: str, *, context: dict[str, Any], data: dict[str, Any]) -> data_entry_flow.FlowHandler:
        """Create a setup flow. handler is a mfa module."""
        ...
    
    async def async_finish_flow(self, flow: data_entry_flow.FlowHandler, result: data_entry_flow.FlowResult) -> data_entry_flow.FlowResult:
        """Complete an mfs setup flow."""
        ...
    


async def async_setup(hass: HomeAssistant) -> None:
    """Init mfa setup flow manager."""
    ...

@callback
@websocket_api.ws_require_user(allow_system_user=False)
def websocket_setup_mfa(hass: HomeAssistant, connection: websocket_api.ActiveConnection, msg: dict[str, Any]) -> None:
    """Return a setup flow for mfa auth module."""
    ...

@callback
@websocket_api.ws_require_user(allow_system_user=False)
def websocket_depose_mfa(hass: HomeAssistant, connection: websocket_api.ActiveConnection, msg: dict[str, Any]) -> None:
    """Remove user from mfa module."""
    ...

