"""
This type stub file was generated by pyright.
"""

from typing import Any

"""Deal with YAML input."""
class UndefinedSubstitution(Exception):
    """Error raised when we find a substitution that is not defined."""
    def __init__(self, input_name: str) -> None:
        """Initialize the undefined substitution exception."""
        ...
    


def extract_inputs(obj: Any) -> set[str]:
    """Extract input from a structure."""
    ...

def substitute(obj: Any, substitutions: dict[str, Any]) -> Any:
    """Substitute values."""
    ...

