"""
This type stub file was generated by pyright.
"""

from typing import Any
from homeassistant.config_entries import ConfigEntry
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers.typing import DiscoveryInfoType

"""Support for MQTT discovery."""
_LOGGER = ...
TOPIC_MATCHER = ...
SUPPORTED_COMPONENTS = ...
MQTT_DISCOVERY_UPDATED = ...
MQTT_DISCOVERY_NEW = ...
MQTT_DISCOVERY_DONE = ...
TOPIC_BASE = ...
MQTT_ORIGIN_INFO_SCHEMA = ...

class MQTTDiscoveryPayload(dict[str, Any]):
    """Class to hold and MQTT discovery payload and discovery data."""

    discovery_data: DiscoveryInfoType
    ...

def clear_discovery_hash(hass: HomeAssistant, discovery_hash: tuple[str, str]) -> None:
    """Clear entry from already discovered list."""
    ...

def set_discovery_hash(hass: HomeAssistant, discovery_hash: tuple[str, str]) -> None:
    """Add entry to already discovered list."""
    ...

@callback
def async_log_discovery_origin_info(
    message: str, discovery_payload: MQTTDiscoveryPayload
) -> None:
    """Log information about the discovery and origin."""
    ...

async def async_start(
    hass: HomeAssistant, discovery_topic: str, config_entry: ConfigEntry
) -> None:
    """Start MQTT Discovery."""
    ...

async def async_stop(hass: HomeAssistant) -> None:
    """Stop MQTT Discovery."""
    ...
