"""
This type stub file was generated by pyright.
"""

import voluptuous as vol
from typing import Any, Protocol
from homeassistant.core import Context, HomeAssistant
from homeassistant.helpers.typing import ConfigType

"""Device action validator."""
class DeviceAutomationActionProtocol(Protocol):
    """Define the format of device_action modules.

    Each module must define either ACTION_SCHEMA or async_validate_action_config.
    """
    ACTION_SCHEMA: vol.Schema
    async def async_validate_action_config(self, hass: HomeAssistant, config: ConfigType) -> ConfigType:
        """Validate config."""
        ...
    
    async def async_call_action_from_config(self, hass: HomeAssistant, config: ConfigType, variables: dict[str, Any], context: Context | None) -> None:
        """Execute a device action."""
        ...
    
    async def async_get_action_capabilities(self, hass: HomeAssistant, config: ConfigType) -> dict[str, vol.Schema]:
        """List action capabilities."""
        ...
    
    async def async_get_actions(self, hass: HomeAssistant, device_id: str) -> list[dict[str, Any]]:
        """List actions."""
        ...
    


async def async_validate_action_config(hass: HomeAssistant, config: ConfigType) -> ConfigType:
    """Validate config."""
    ...

async def async_call_action_from_config(hass: HomeAssistant, config: ConfigType, variables: dict[str, Any], context: Context | None) -> None:
    """Execute a device action."""
    ...

