"""
This type stub file was generated by pyright.
"""

from homeassistant.exceptions import HomeAssistantError

"""Device automation exceptions."""
class InvalidDeviceAutomationConfig(HomeAssistantError):
    """When device automation config is invalid."""
    ...


class DeviceNotFound(HomeAssistantError):
    """When referenced device not found."""
    ...


class EntityNotFound(HomeAssistantError):
    """When referenced entity not found."""
    ...


