"""
This type stub file was generated by pyright.
"""

import datetime as dt
from dataclasses import dataclass
from homeassistant.data_entry_flow import BaseServiceInfo

"""MQTT Discovery data."""
ReceivePayloadType = str | bytes
@dataclass(slots=True)
class MqttServiceInfo(BaseServiceInfo):
    """Prepared info from mqtt entries."""
    topic: str
    payload: ReceivePayloadType
    qos: int
    retain: bool
    subscribed_topic: str
    timestamp: dt.datetime
    ...


