"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable, Hashable

"""
This type stub file was generated by pyright.
"""
CALLABLE_T = ...

class Registry(dict):
    """Registry of items."""

    def register(self, name: Hashable) -> Callable[[CALLABLE_T], CALLABLE_T]:
        """Return decorator to register item with a specific name."""
        ...
