"""
This type stub file was generated by pyright.
"""

from concurrent.futures import ThreadPoolExecutor
from threading import Thread
from typing import Any

"""Executor util helpers."""
_LOGGER = ...
MAX_LOG_ATTEMPTS = ...
_JOIN_ATTEMPTS = ...
EXECUTOR_SHUTDOWN_TIMEOUT = ...
def join_or_interrupt_threads(threads: set[Thread], timeout: float, log: bool) -> set[Thread]:
    """Attempt to join or interrupt a set of threads."""
    ...

class InterruptibleThreadPoolExecutor(ThreadPoolExecutor):
    """A ThreadPoolExecutor instance that will not deadlock on shutdown."""
    def shutdown(self, *args: Any, **kwargs: Any) -> None:
        """Shutdown with interrupt support added."""
        ...
    
    def join_threads_or_timeout(self) -> None:
        """Join threads or timeout."""
        ...
    


