"""
This type stub file was generated by pyright.
"""

"""Unit system helper class and methods."""
LENGTH_UNITS = ...
MASS_UNITS: tuple[str, ...] = ...
PRESSURE_UNITS = ...
VOLUME_UNITS = ...
TEMPERATURE_UNITS: tuple[str, ...] = ...

def is_valid_unit(unit: str, unit_type: str) -> bool:
    """Check if the unit is valid for it's type."""
    ...

class UnitSystem:
    """A container for units of measure."""

    def __init__(
        self,
        name: str,
        temperature: str,
        length: str,
        volume: str,
        mass: str,
        pressure: str,
    ) -> None:
        """Initialize the unit system object."""
        ...
    @property
    def is_metric(self) -> bool:
        """Determine if this is the metric unit system."""
        ...
    def temperature(self, temperature: float, from_unit: str) -> float:
        """Convert the given temperature to this unit system."""
        ...
    def length(self, length: float | None, from_unit: str) -> float:
        """Convert the given length to this unit system."""
        ...
    def pressure(self, pressure: float | None, from_unit: str) -> float:
        """Convert the given pressure to this unit system."""
        ...
    def volume(self, volume: float | None, from_unit: str) -> float:
        """Convert the given volume to this unit system."""
        ...
    def as_dict(self) -> dict[str, str]:
        """Convert the unit system to a dictionary."""
        ...

METRIC_SYSTEM = ...
IMPERIAL_SYSTEM = ...
