"""
This type stub file was generated by pyright.
"""

"""Volume conversion util functions."""
VALID_UNITS: tuple[str, ...] = ...

def liter_to_gallon(liter: float) -> float:
    """Convert a volume measurement in Liter to Gallon."""
    ...

def gallon_to_liter(gallon: float) -> float:
    """Convert a volume measurement in Gallon to Liter."""
    ...

def cubic_meter_to_cubic_feet(cubic_meter: float) -> float:
    """Convert a volume measurement in cubic meter to cubic feet."""
    ...

def cubic_feet_to_cubic_meter(cubic_feet: float) -> float:
    """Convert a volume measurement in cubic feet to cubic meter."""
    ...

def convert(volume: float, from_unit: str, to_unit: str) -> float:
    """Convert a temperature from one unit to another."""
    ...
