"""
This type stub file was generated by pyright.
"""

from homeassistant.exceptions import HomeAssistantError

"""Errors for the Media Player component."""
class MediaPlayerException(HomeAssistantError):
    """Base class for Media Player exceptions."""
    ...


class BrowseError(MediaPlayerException):
    """Error while browsing."""
    ...


