"""
This type stub file was generated by pyright.
"""

from typing import Any
from homeassistant.util.executor import InterruptibleThreadPoolExecutor

"""Database executor helpers."""
class DBInterruptibleThreadPoolExecutor(InterruptibleThreadPoolExecutor):
    """A database instance that will not deadlock on shutdown."""
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Init the executor with a shutdown hook support."""
        ...
    


