"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from . import Recorder

"""Purge repack helper."""
if TYPE_CHECKING:
    ...
_LOGGER = ...
def repack_database(instance: Recorder) -> None:
    """Repack based on engine type."""
    ...

