"""
This type stub file was generated by pyright.
"""

import voluptuous as vol
from __future__ import annotations
from typing import Final, cast
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers import config_validation as cv
from homeassistant.helpers.typing import ConfigType
from homeassistant.loader import bind_hass
from . import commands, connection, const, decorators, http, messages
from .connection import ActiveConnection, current_connection
from .const import AsyncWebSocketCommandHandler, ERR_HOME_ASSISTANT_ERROR, ERR_INVALID_FORMAT, ERR_NOT_FOUND, ERR_NOT_SUPPORTED, ERR_SERVICE_VALIDATION_ERROR, ERR_TEMPLATE_ERROR, ERR_TIMEOUT, ERR_UNAUTHORIZED, ERR_UNKNOWN_COMMAND, ERR_UNKNOWN_ERROR, WebSocketCommandHandler
from .decorators import async_response, require_admin, websocket_command, ws_require_user
from .messages import BASE_COMMAND_MESSAGE_SCHEMA, error_message, event_message, result_message

"""WebSocket based API for Home Assistant."""
DOMAIN: Final = ...
DEPENDENCIES: Final[tuple[str]] = ...
CONFIG_SCHEMA = ...
@bind_hass
@callback
def async_register_command(hass: HomeAssistant, command_or_handler: str | const.WebSocketCommandHandler, handler: const.WebSocketCommandHandler | None = ..., schema: vol.Schema | None = ...) -> None:
    """Register a websocket command."""
    ...

async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool:
    """Initialize the websocket API."""
    ...

