"""
This type stub file was generated by pyright.
"""

from collections.abc import Awaitable, Callable
from logging import Logger
from typing import Any

from homeassistant.core import HomeAssistant, callback

"""Debounce helper."""

class Debouncer:
    """Class to rate limit calls to a specific command."""

    def __init__(
        self,
        hass: HomeAssistant,
        logger: Logger,
        *,
        cooldown: float,
        immediate: bool,
        function: Callable[..., Awaitable[Any]] | None = ...
    ) -> None:
        """Initialize debounce.

        immediate: indicate if the function needs to be called right away and
                   wait <cooldown> until executing next invocation.
        function: optional and can be instantiated later.
        """
        ...
    @property
    def function(self) -> Callable[..., Awaitable[Any]] | None:
        """Return the function being wrapped by the Debouncer."""
        ...
    @function.setter
    def function(self, function: Callable[..., Awaitable[Any]]) -> None:
        """Update the function being wrapped by the Debouncer."""
        ...
    async def async_call(self) -> None:
        """Call the function."""
        ...
    @callback
    def async_cancel(self) -> None:
        """Cancel any scheduled call."""
        ...
