"""
This type stub file was generated by pyright.
"""

from typing import Any, NamedTuple
from homeassistant.core import HomeAssistant, callback
from homeassistant.loader import bind_hass

"""The discovery flow helper."""
FLOW_INIT_LIMIT = ...
DISCOVERY_FLOW_DISPATCHER = ...
@bind_hass
@callback
def async_create_flow(hass: HomeAssistant, domain: str, context: dict[str, Any], data: Any) -> None:
    """Create a discovery flow."""
    ...

class PendingFlowKey(NamedTuple):
    """Key for pending flows."""
    domain: str
    source: str
    ...


class PendingFlowValue(NamedTuple):
    """Value for pending flows."""
    context: dict[str, Any]
    data: Any
    ...


class FlowDispatcher:
    """Dispatch discovery flows."""
    def __init__(self, hass: HomeAssistant) -> None:
        """Init the discovery dispatcher."""
        ...
    
    @callback
    def async_setup(self) -> None:
        """Set up the flow disptcher."""
        ...
    
    @callback
    def async_create(self, domain: str, context: dict[str, Any], data: Any) -> None:
        """Create and add or queue a flow."""
        ...
    


