"""
This type stub file was generated by pyright.
"""

from functools import lru_cache

"""A class to hold entity values."""
_MAX_EXPECTED_ENTITIES = ...

class EntityValues:
    """Class to store entity id based values.

    This class is expected to only be used infrequently
    as it caches all entity ids up to _MAX_EXPECTED_ENTITIES.

    The cache includes `self` so it is important to
    only use this in places where usage of `EntityValues` is immortal.
    """
    def __init__(
        self,
        exact: dict[str, dict[str, str]] | None = ...,
        domain: dict[str, dict[str, str]] | None = ...,
        glob: dict[str, dict[str, str]] | None = ...,
    ) -> None:
        """Initialize an EntityConfigDict."""
        ...

    @lru_cache(maxsize=_MAX_EXPECTED_ENTITIES)
    def get(self, entity_id: str) -> dict[str, str]:
        """Get config for an entity id."""
        ...
