"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from dataclasses import dataclass
from traceback import FrameSummary
from typing import TypeVar
from homeassistant.exceptions import HomeAssistantError

"""Provide frame helper for finding the current frame context."""
_LOGGER = ...
_REPORTED_INTEGRATIONS: set[str] = ...
_CallableT = TypeVar("_CallableT", bound=Callable)

@dataclass(kw_only=True)
class IntegrationFrame:
    """Integration frame container."""

    custom_integration: bool
    frame: FrameSummary
    integration: str
    module: str | None
    relative_filename: str
    ...

def get_integration_frame(exclude_integrations: set | None = ...) -> IntegrationFrame:
    """Return the frame, integration and integration path of the current stack frame."""
    ...

class MissingIntegrationFrame(HomeAssistantError):
    """Raised when no integration is found in the frame."""

    ...

def report(
    what: str,
    exclude_integrations: set | None = ...,
    error_if_core: bool = ...,
    level: int = ...,
) -> None:
    """Report incorrect usage.

    Async friendly.
    """
    ...

def warn_use(func: _CallableT, what: str) -> _CallableT:
    """Mock a function to warn when it was about to be used."""
    ...
