"""
This type stub file was generated by pyright.
"""

from traceback import FrameSummary

from homeassistant.exceptions import HomeAssistantError

"""Provide frame helper for finding the current frame context."""
_LOGGER = ...
CALLABLE_T = ...

def get_integration_frame(
    exclude_integrations: set | None = ...,
) -> tuple[FrameSummary, str, str]:
    """Return the frame, integration and integration path of the current stack frame."""
    ...

class MissingIntegrationFrame(HomeAssistantError):
    """Raised when no integration is found in the frame."""

    ...

def report(what: str) -> None:
    """Report incorrect usage.

    Async friendly.
    """
    ...

def report_integration(
    what: str, integration_frame: tuple[FrameSummary, str, str]
) -> None:
    """Report incorrect usage in an integration.

    Async friendly.
    """
    ...

def warn_use(func: CALLABLE_T, what: str) -> CALLABLE_T:
    """Mock a function to warn when it was about to be used."""
    ...
