"""
This type stub file was generated by pyright.
"""

from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from typing import Any
from homeassistant.core import HomeAssistant
from homeassistant.loader import bind_hass

"""Helpers to help with integration platforms."""
_LOGGER = ...
DATA_INTEGRATION_PLATFORMS = ...
@dataclass(slots=True, frozen=True)
class IntegrationPlatform:
    """An integration platform."""
    platform_name: str
    process_platform: Callable[[HomeAssistant, str, Any], Awaitable[None]]
    seen_components: set[str]
    ...


@bind_hass
async def async_process_integration_platforms(hass: HomeAssistant, platform_name: str, process_platform: Callable[[HomeAssistant, str, Any], Awaitable[None]]) -> None:
    """Process a specific platform for all current and future loaded integrations."""
    ...

