"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable

from homeassistant.core import CALLBACK_TYPE, HomeAssistant
from homeassistant.helpers.typing import ConfigType, TemplateVarsType

"""Triggers."""
_PLATFORM_ALIASES = ...

async def async_validate_trigger_config(
    hass: HomeAssistant, trigger_config: list[ConfigType]
) -> list[ConfigType]:
    """Validate triggers."""
    ...

async def async_initialize_triggers(
    hass: HomeAssistant,
    trigger_config: list[ConfigType],
    action: Callable,
    domain: str,
    name: str,
    log_cb: Callable,
    home_assistant_start: bool = ...,
    variables: TemplateVarsType = ...,
) -> CALLBACK_TYPE | None:
    """Initialize triggers."""
    ...
