"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from awesomeversion import AwesomeVersion
from ..const import SupportedDialect

"""Models for the database in the Recorder."""
class UnsupportedDialect(Exception):
    """The dialect or its version is not supported."""
    ...


@dataclass
class DatabaseEngine:
    """Properties of the database engine."""
    dialect: SupportedDialect
    optimizer: DatabaseOptimizer
    max_bind_vars: int
    version: AwesomeVersion | None
    ...


@dataclass
class DatabaseOptimizer:
    """Properties of the database optimizer for the configured database engine."""
    slow_range_in_select: bool
    ...


