"""
This type stub file was generated by pyright.
"""

"""Models events in for Recorder."""
def extract_event_type_ids(event_type_to_event_type_id: dict[str, int | None]) -> list[int]:
    """Extract event_type ids from event_type_to_event_type_id."""
    ...

