"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING

import attr
from homeassistant.helpers import device_registry as dev_reg
from homeassistant.helpers import entity_registry as ent_reg

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING: ...

@attr.s(slots=True)
class PermissionLookup:
    """Class to hold data for permission lookups."""

    entity_registry: ent_reg.EntityRegistry = ...
    device_registry: dev_reg.DeviceRegistry = ...
