"""
This type stub file was generated by pyright.
"""

from typing import Mapping, Union

"""
This type stub file was generated by pyright.
"""
ValueType = ...
SubCategoryDict = Mapping[str, ValueType]
SubCategoryType = Union[SubCategoryDict, bool, None]
CategoryType = ...
PolicyType = Mapping[str, CategoryType]
