"""
This type stub file was generated by pyright.
"""

import logging
import re
import voluptuous as vol
import homeassistant.helpers.config_validation as cv
from __future__ import annotations
from homeassistant.const import EVENT_LOGGING_CHANGED
from homeassistant.core import HomeAssistant, ServiceCall, callback
from homeassistant.helpers.typing import ConfigType
from . import websocket_api
from .const import ATTR_LEVEL, DOMAIN, LOGGER_DEFAULT, LOGGER_FILTERS, LOGGER_LOGS, LOGSEVERITY, SERVICE_SET_DEFAULT_LEVEL, SERVICE_SET_LEVEL
from .helpers import LoggerDomainConfig, LoggerSettings, set_default_log_level, set_log_levels

"""Support for setting the level of logging for components."""
_VALID_LOG_LEVEL = ...
SERVICE_SET_DEFAULT_LEVEL_SCHEMA = ...
SERVICE_SET_LEVEL_SCHEMA = ...
CONFIG_SCHEMA = ...
async def async_setup(hass: HomeAssistant, config: ConfigType) -> bool:
    """Set up the logger component."""
    ...

