"""
This type stub file was generated by pyright.
"""

from typing import Final

from aiohttp.web import Application
from homeassistant.core import callback

"""
This type stub file was generated by pyright.
"""
ALLOWED_CORS_HEADERS: Final[list[str]] = ...
VALID_CORS_TYPES: Final = ...

@callback
def setup_cors(app: Application, origins: list[str]) -> None:
    """Set up CORS."""
    ...
