"""
This type stub file was generated by pyright.
"""

from typing import Final

from aiohttp.web import Application
from homeassistant.core import callback

"""
This type stub file was generated by pyright.
"""
_LOGGER = ...
FILTERS: Final = ...

@callback
def setup_security_filter(app: Application) -> None:
    """Create security filter middleware for the app."""
    ...
