"""
This type stub file was generated by pyright.
"""

from homeassistant.core import callback
from .models import Adapter

"""Network helper class for the network integration."""
_LOGGER = ...
async def async_load_adapters() -> list[Adapter]:
    """Load adapters."""
    ...

def enable_adapters(adapters: list[Adapter], enabled_interfaces: list[str]) -> bool:
    """Enable configured adapters."""
    ...

def enable_auto_detected_adapters(adapters: list[Adapter]) -> None:
    """Enable auto detected adapters."""
    ...

@callback
def async_get_source_ip(target_ip: str) -> str | None:
    """Return the source ip that will reach target_ip."""
    ...

