"""
This type stub file was generated by pyright.
"""

import voluptuous as vol
from typing import Any
from homeassistant.components import websocket_api
from homeassistant.components.websocket_api.connection import ActiveConnection
from homeassistant.core import HomeAssistant, callback
from .const import NETWORK_CONFIG_SCHEMA

"""The Network Configuration integration websocket commands."""
@callback
def async_register_websocket_commands(hass: HomeAssistant) -> None:
    """Register network websocket commands."""
    ...

@websocket_api.require_admin
@websocket_api.websocket_command({ vol.Required("type"): "network" })
@websocket_api.async_response
async def websocket_network_adapters(hass: HomeAssistant, connection: ActiveConnection, msg: dict[str, Any]) -> None:
    """Return network preferences."""
    ...

@websocket_api.require_admin
@websocket_api.websocket_command({ vol.Required("type"): "network/configure",vol.Required("config", default={}): NETWORK_CONFIG_SCHEMA })
@websocket_api.async_response
async def websocket_network_adapters_configure(hass: HomeAssistant, connection: ActiveConnection, msg: dict[str, Any]) -> None:
    """Update network config."""
    ...

