"""
This type stub file was generated by pyright.
"""

from .models import HaZeroconf

"""Zeroconf usage utility to warn about multiple instances."""
def install_multiple_zeroconf_catcher(hass_zc: HaZeroconf) -> None:
    """Wrap the Zeroconf class to return the shared instance.

    Only if if multiple instances are detected.
    """
    ...

