"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from typing import Any

"""
This type stub file was generated by pyright.
"""

def deprecated_substitute(substitute_name: str) -> Callable[..., Callable]:
    """Help migrate properties to new names.

    When a property is added to replace an older property, this decorator can
    be added to the new property, listing the old property as the substitute.
    If the old property is defined, its value will be used instead, and a log
    warning will be issued alerting the user of the impending change.
    """
    ...

def get_deprecated(
    config: dict[str, Any], new_name: str, old_name: str, default: Any | None = ...
) -> Any | None:
    """Allow an old config name to be deprecated with a replacement.

    If the new config isn't found, but the old one is, the old value is used
    and a warning is issued to the user.
    """
    ...

def deprecated_class(replacement: str) -> Any:
    """Mark class as deprecated and provide a replacement class to be used instead."""
    ...

def deprecated_function(replacement: str) -> Callable[..., Callable]:
    """Mark function as deprecated and provide a replacement function to be used instead."""
    ...
