"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Dict, Mapping, Optional, Tuple, Union

"""
This type stub file was generated by pyright.
"""
GPSType = Tuple[float, float]
ConfigType = Dict[str, Any]
ContextType = ...
DiscoveryInfoType = Dict[str, Any]
EventType = ...
ServiceDataType = Dict[str, Any]
StateType = Union[None, str, int, float]
TemplateVarsType = Optional[Mapping[str, Any]]
QueryType = Any

class UndefinedType(Enum):
    """Singleton type for use with not set sentinel values."""

    _singleton = ...

UNDEFINED = ...
HomeAssistantType = ...
ServiceCallType = ...
