"""
This type stub file was generated by pyright.
"""

from .types import PolicyType

"""Merging of policies."""
def merge_policies(policies: list[PolicyType]) -> PolicyType:
    """Merge policies."""
    ...

