"""
This type stub file was generated by pyright.
"""

from typing import Mapping, Union

"""Common code for permissions."""
ValueType = (Union[Mapping[str, bool], bool, None],)
SubCategoryDict = Mapping[str, ValueType]
SubCategoryType = Union[SubCategoryDict, bool, None]
CategoryType = (
    Union[Mapping[str, SubCategoryType], Mapping[str, ValueType], bool, None],
)
PolicyType = Mapping[str, CategoryType]
