"""
This type stub file was generated by pyright.
"""

from homeassistant.components.http import HomeAssistantView
from homeassistant.core import HomeAssistant

"""Implement the Ingress Panel feature for Hass.io Add-ons."""
_LOGGER = ...
async def async_setup_addon_panel(hass: HomeAssistant, hassio): # -> None:
    """Add-on Ingress Panel setup."""
    ...

class HassIOAddonPanel(HomeAssistantView):
    """Hass.io view to handle base part."""
    name = ...
    url = ...
    def __init__(self, hass, hassio) -> None:
        """Initialize WebView."""
        ...
    
    async def post(self, request, addon): # -> Response:
        """Handle new add-on panel requests."""
        ...
    
    async def delete(self, request, addon): # -> Response:
        """Handle remove add-on panel requests."""
        ...
    
    async def get_panels(self): # -> dict[Unknown, Unknown]:
        """Return panels add-on info data."""
        ...
    


