---
name: Devcontainer-based CI
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build-devcontainer:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          imageName: ghcr.io/${{ github.repository }}-devcontainer
          push: filter
          refFilterForPush: refs/heads/main

  just-check:
    needs: build-devcontainer
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate justfile
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          push: never
          runCmd: just just-check

  format:
    needs: just-check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run formatting
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          push: never
          runCmd: |
            just just-format
            just ruff-format

  quick-lint:
    needs: just-check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run quick-lint
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          push: never
          runCmd: |
            just hadolint
            just pyright
            just renovate-validate
            just ruff-check
            just yamllint

  pytest:
    needs: just-check
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run pytest
        uses: devcontainers/ci@8bf61b26e9c3a98f69cb6ce2f88d24ff59b785c6 # v0.3.1900000417
        with:
          cacheFrom: ghcr.io/${{ github.repository }}-devcontainer
          push: never
          runCmd: just pytest
